// Command genvectors generates the shared cross-language test vectors
// consumed by the relay's own tests and vendored into amallo and web (see
// spec/PROTOCOL.md and the build plan's Step 1). Vectors are generated by
// calling the real Go proto/wire code, so they self-validate by
// construction; the point of publishing them is letting Rust and
// TypeScript implementations prove they agree with this one, byte for
// byte, at every derivation step.
//
// Inputs are derived deterministically from fixed seed strings (via
// SHA-256) rather than crypto/rand, so re-running this command reproduces
// byte-identical output — a real requirement, since the vectors are
// committed and diffed in review.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/OpenCharUI/relay/internal/proto"
	"github.com/OpenCharUI/relay/internal/wire"
)

func main() {
	outDir := "testdata/vectors"
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fatal(err)
	}

	write(outDir, "frame_outer.json", genFrameOuter())
	write(outDir, "frame_inner.json", genFrameInner())
	write(outDir, "handshake.json", genHandshake())
	write(outDir, "aead.json", genAEAD())
	write(outDir, "reqresp.json", genReqResp())
	write(outDir, "session.json", genSession())

	fmt.Println("vectors written to", outDir)
}

func write(dir, name string, v any) {
	f, err := os.Create(filepath.Join(dir, name))
	if err != nil {
		fatal(err)
	}
	defer f.Close()
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "genvectors:", err)
	os.Exit(1)
}

// --- deterministic seeding helpers -----------------------------------------

// seed produces reproducible "random" bytes of length n from a label, via
// repeated SHA-256 (a simple, transparent, non-cryptographic-purpose
// expansion — the values only need to be fixed and plausible-looking, not
// secure, since these are test fixtures).
func seed(label string, n int) []byte {
	out := make([]byte, 0, n)
	counter := 0
	for len(out) < n {
		h := sha256.Sum256([]byte(fmt.Sprintf("opencharui-vectors-v1:%s:%d", label, counter)))
		out = append(out, h[:]...)
		counter++
	}
	return out[:n]
}

func hx(b []byte) string { return hex.EncodeToString(b) }

func mustHex(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		fatal(err)
	}
	return b
}

// deterministicEphemeral builds an Ephemeral from a seeded scalar. P-256's
// order is so close to 2^256 that a SHA-256 output is invalid with
// negligible-but-nonzero probability; fall back to re-seeding if so, so
// this never silently produces a different key type than a random one
// would.
func deterministicEphemeral(label string) *proto.Ephemeral {
	for i := 0; ; i++ {
		scalar := seed(fmt.Sprintf("%s#%d", label, i), 32)
		eph, err := proto.EphemeralFromScalar(scalar)
		if err == nil {
			return eph
		}
	}
}

// --- frame_outer.json --------------------------------------------------------

type frameOuterVectors struct {
	Encode []frameOuterEncodeCase `json:"encode"`
	Parse  []frameOuterParseCase  `json:"parse"`
}

type frameOuterEncodeCase struct {
	Name       string `json:"name"`
	ChannelHex string `json:"channel_hex"`
	PayloadHex string `json:"payload_hex"`
	WantHex    string `json:"want_hex"`
}

type frameOuterParseCase struct {
	Name           string `json:"name"`
	RawHex         string `json:"raw_hex"`
	WantChannelHex string `json:"want_channel_hex,omitempty"`
	WantPayloadHex string `json:"want_payload_hex,omitempty"`
	ExpectError    string `json:"expect_error,omitempty"`
}

func genFrameOuter() frameOuterVectors {
	var v frameOuterVectors

	for _, ch := range []wire.Channel{wire.ChannelControl, wire.ChannelCiphertext, wire.ChannelHandshake} {
		payload := seed(fmt.Sprintf("outer-payload-%d", ch), 12)
		encoded := wire.EncodeOuter(ch, payload)
		v.Encode = append(v.Encode, frameOuterEncodeCase{
			Name:       fmt.Sprintf("encode/channel_0x%02x", byte(ch)),
			ChannelHex: hx([]byte{byte(ch)}),
			PayloadHex: hx(payload),
			WantHex:    hx(encoded),
		})
		v.Parse = append(v.Parse, frameOuterParseCase{
			Name:           fmt.Sprintf("parse/channel_0x%02x", byte(ch)),
			RawHex:         hx(encoded),
			WantChannelHex: hx([]byte{byte(ch)}),
			WantPayloadHex: hx(payload),
		})
	}

	v.Parse = append(v.Parse,
		frameOuterParseCase{Name: "parse/empty", RawHex: "", ExpectError: "frame_too_short"},
		frameOuterParseCase{Name: "parse/one_byte", RawHex: "01", ExpectError: "frame_too_short"},
		frameOuterParseCase{Name: "parse/reserved_bit_1", RawHex: "0102aa", ExpectError: "reserved_flags_set"},
		frameOuterParseCase{Name: "parse/reserved_bit_7", RawHex: "0180aa", ExpectError: "reserved_flags_set"},
		frameOuterParseCase{Name: "parse/conn_id_present_v1", RawHex: "010100000000000000010203", ExpectError: "conn_id_not_v1"},
	)
	return v
}

// --- frame_inner.json --------------------------------------------------------

type frameInnerVectors struct {
	Encode []frameInnerEncodeCase `json:"encode"`
	Decode []frameInnerDecodeCase `json:"decode"`
}

type frameInnerEncodeCase struct {
	Name        string `json:"name"`
	TypeHex     string `json:"type_hex"`
	StreamID    uint32 `json:"stream_id"`
	PayloadHex  string `json:"payload_hex"`
	WantHex     string `json:"want_hex,omitempty"`
	ExpectError string `json:"expect_error,omitempty"`
}

type innerFrameOut struct {
	TypeHex    string `json:"type_hex"`
	StreamID   uint32 `json:"stream_id"`
	PayloadHex string `json:"payload_hex"`
}

type frameInnerDecodeCase struct {
	Name        string          `json:"name"`
	BufHex      string          `json:"buf_hex"`
	WantFrames  []innerFrameOut `json:"want_frames,omitempty"`
	ExpectError string          `json:"expect_error,omitempty"`
}

func genFrameInner() frameInnerVectors {
	var v frameInnerVectors

	single := wire.InnerFrame{Type: wire.InnerReq, StreamID: 1, Payload: []byte(`{"m":"GET","p":"/api/tags"}`)}
	buf, err := wire.EncodeInner(nil, single)
	if err != nil {
		fatal(err)
	}
	v.Encode = append(v.Encode, frameInnerEncodeCase{
		Name: "encode/req", TypeHex: hx([]byte{byte(single.Type)}), StreamID: single.StreamID,
		PayloadHex: hx(single.Payload), WantHex: hx(buf),
	})
	v.Decode = append(v.Decode, frameInnerDecodeCase{
		Name: "decode/req", BufHex: hx(buf),
		WantFrames: []innerFrameOut{{TypeHex: hx([]byte{byte(single.Type)}), StreamID: single.StreamID, PayloadHex: hx(single.Payload)}},
	})

	// The batching path: three frames concatenated in one payload.
	frames := []wire.InnerFrame{
		{Type: wire.InnerReq, StreamID: 3, Payload: []byte(`{"m":"POST","p":"/api/chat","h":[["content-type","application/json"]]}`)},
		{Type: wire.InnerReqBody, StreamID: 3, Payload: []byte(`{"model":"llama3"}`)},
		{Type: wire.InnerReqEnd, StreamID: 3, Payload: nil},
	}
	var concat []byte
	var wantFrames []innerFrameOut
	for _, f := range frames {
		concat, err = wire.EncodeInner(concat, f)
		if err != nil {
			fatal(err)
		}
		wantFrames = append(wantFrames, innerFrameOut{TypeHex: hx([]byte{byte(f.Type)}), StreamID: f.StreamID, PayloadHex: hx(f.Payload)})
	}
	v.Decode = append(v.Decode, frameInnerDecodeCase{
		Name: "decode/three_frames_concatenated", BufHex: hx(concat), WantFrames: wantFrames,
	})

	// Zero-length payload, and boundary stream IDs.
	zeroLen, _ := wire.EncodeInner(nil, wire.InnerFrame{Type: wire.InnerReqEnd, StreamID: 0, Payload: nil})
	v.Decode = append(v.Decode, frameInnerDecodeCase{
		Name: "decode/zero_length_payload", BufHex: hx(zeroLen),
		WantFrames: []innerFrameOut{{TypeHex: hx([]byte{byte(wire.InnerReqEnd)}), StreamID: 0, PayloadHex: ""}},
	})
	maxStream, _ := wire.EncodeInner(nil, wire.InnerFrame{Type: wire.InnerCancel, StreamID: 0xFFFFFFFF, Payload: nil})
	v.Decode = append(v.Decode, frameInnerDecodeCase{
		Name: "decode/max_stream_id", BufHex: hx(maxStream),
		WantFrames: []innerFrameOut{{TypeHex: hx([]byte{byte(wire.InnerCancel)}), StreamID: 0xFFFFFFFF, PayloadHex: ""}},
	})

	// Negative cases.
	v.Decode = append(v.Decode,
		frameInnerDecodeCase{Name: "decode/truncated_header", BufHex: hx(buf[:5]), ExpectError: "inner_frame_too_short"},
		frameInnerDecodeCase{Name: "decode/truncated_payload", BufHex: hx(buf[:len(buf)-2]), ExpectError: "inner_truncated"},
	)
	for _, typ := range []wire.InnerType{wire.InnerWindowUpdate, wire.InnerPing, wire.InnerPong} {
		reserved := make([]byte, 8)
		reserved[0] = byte(typ)
		v.Decode = append(v.Decode, frameInnerDecodeCase{
			Name: fmt.Sprintf("decode/reserved_type_0x%02x", byte(typ)), BufHex: hx(reserved), ExpectError: "inner_reserved_type",
		})
		v.Encode = append(v.Encode, frameInnerEncodeCase{
			Name: fmt.Sprintf("encode/reserved_type_0x%02x", byte(typ)), TypeHex: hx([]byte{byte(typ)}), StreamID: 1,
			ExpectError: "inner_reserved_type",
		})
	}

	return v
}

// --- handshake.json -----------------------------------------------------------

type handshakeInputs struct {
	PairIDHex         string `json:"pair_id_hex"`
	PSKHex            string `json:"psk_hex"`
	AgentEphScalarHex string `json:"agent_eph_priv_raw_hex"`
	WebEphScalarHex   string `json:"web_eph_priv_raw_hex"`
	AgentNonceHex     string `json:"agent_nonce_hex"`
	WebNonceHex       string `json:"web_nonce_hex"`
}

type handshakeExpected struct {
	KMacHex         string `json:"k_mac_hex"`
	AgentEpkHex     string `json:"agent_epk_hex"`
	WebEpkHex       string `json:"web_epk_hex"`
	HelloAgentHex   string `json:"hello_agent_hex"`
	HelloWebHex     string `json:"hello_web_hex"`
	TranscriptHex   string `json:"transcript_hex"`
	EcdhXHex        string `json:"ecdh_x_hex"`
	PskIkmHex       string `json:"psk_ikm_hex"`
	KA2WHex         string `json:"k_a2w_hex"`
	KW2AHex         string `json:"k_w2a_hex"`
	NpA2WHex        string `json:"np_a2w_hex"`
	NpW2AHex        string `json:"np_w2a_hex"`
	ConfirmAgentHex string `json:"confirm_agent_hex"`
	ConfirmWebHex   string `json:"confirm_web_hex"`
}

type handshakeCase struct {
	Name        string             `json:"name"`
	Inputs      handshakeInputs    `json:"inputs"`
	Expected    *handshakeExpected `json:"expected,omitempty"`
	ExpectError string             `json:"expect_error,omitempty"`
	// For verify-only negative cases: a directly-supplied (possibly
	// tampered/malformed) HELLO to feed to VerifyHello, plus the role the
	// *verifier* holds (the peer role is whatever's encoded in the HELLO).
	VerifyRawHelloHex string `json:"verify_raw_hello_hex,omitempty"`
	VerifyOwnRoleHex  string `json:"verify_own_role_hex,omitempty"`
	VerifyPairIDHex   string `json:"verify_pair_id_hex,omitempty"`
}

func genHandshake() []handshakeCase {
	var cases []handshakeCase

	pairID := seed("basic-pair-id", 16)
	psk := seed("basic-psk", 32)
	agentEph := deterministicEphemeral("basic-agent-eph")
	webEph := deterministicEphemeral("basic-web-eph")
	agentNonce := seed("basic-agent-nonce", 32)
	webNonce := seed("basic-web-nonce", 32)

	var pairIDArr [16]byte
	copy(pairIDArr[:], pairID)
	var agentNonceArr, webNonceArr [32]byte
	copy(agentNonceArr[:], agentNonce)
	copy(webNonceArr[:], webNonce)

	helloAgent, err := proto.BuildHello(psk, proto.RoleAgent, pairIDArr, agentEph.PublicKeyBytes(), agentNonceArr)
	if err != nil {
		fatal(err)
	}
	helloWeb, err := proto.BuildHello(psk, proto.RoleClient, pairIDArr, webEph.PublicKeyBytes(), webNonceArr)
	if err != nil {
		fatal(err)
	}
	transcript := proto.Transcript(helloAgent, helloWeb)
	ecdhX, err := agentEph.ECDH(webEph.PublicKeyBytes())
	if err != nil {
		fatal(err)
	}
	if webX, err := webEph.ECDH(agentEph.PublicKeyBytes()); err != nil || hx(webX) != hx(ecdhX) {
		fatal(fmt.Errorf("ECDH mismatch between agent and web computation"))
	}
	pskIKM := proto.PSKIKM(psk, transcript)
	keys, err := proto.DeriveSession(psk, transcript, ecdhX)
	if err != nil {
		fatal(err)
	}
	confirmAgent := proto.BuildConfirm(keys.PRK, proto.RoleAgent)
	confirmWeb := proto.BuildConfirm(keys.PRK, proto.RoleClient)

	// Self-check before publishing: every implementation's VerifyHello and
	// VerifyConfirm must accept what BuildHello/BuildConfirm produced.
	if _, err := proto.VerifyHello(psk, helloWeb, pairIDArr, proto.RoleAgent); err != nil {
		fatal(fmt.Errorf("self-check: agent verifying web hello: %w", err))
	}
	if _, err := proto.VerifyHello(psk, helloAgent, pairIDArr, proto.RoleClient); err != nil {
		fatal(fmt.Errorf("self-check: web verifying agent hello: %w", err))
	}
	if err := proto.VerifyConfirm(keys.PRK, confirmAgent, proto.RoleAgent); err != nil {
		fatal(fmt.Errorf("self-check: verifying agent confirm: %w", err))
	}
	if err := proto.VerifyConfirm(keys.PRK, confirmWeb, proto.RoleClient); err != nil {
		fatal(fmt.Errorf("self-check: verifying web confirm: %w", err))
	}

	cases = append(cases, handshakeCase{
		Name: "handshake/basic",
		Inputs: handshakeInputs{
			PairIDHex: hx(pairID), PSKHex: hx(psk),
			AgentEphScalarHex: hx(rawScalar(agentEph)), WebEphScalarHex: hx(rawScalar(webEph)),
			AgentNonceHex: hx(agentNonce), WebNonceHex: hx(webNonce),
		},
		Expected: &handshakeExpected{
			KMacHex: hx(proto.KMac(psk)), AgentEpkHex: hx(agentEph.PublicKeyBytes()), WebEpkHex: hx(webEph.PublicKeyBytes()),
			HelloAgentHex: hx(helloAgent), HelloWebHex: hx(helloWeb), TranscriptHex: hx(transcript[:]),
			EcdhXHex: hx(ecdhX), PskIkmHex: hx(pskIKM),
			KA2WHex: hx(keys.KA2W), KW2AHex: hx(keys.KW2A), NpA2WHex: hx(keys.NPA2W), NpW2AHex: hx(keys.NPW2A),
			ConfirmAgentHex: hx(confirmAgent), ConfirmWebHex: hx(confirmWeb),
		},
	})

	// --- Negative verify-only cases, built from the "basic" fixtures above ---

	tamperedMAC := append([]byte(nil), helloAgent...)
	tamperedMAC[len(tamperedMAC)-1] ^= 0xFF
	mustReject("verify/bad_mac", psk, tamperedMAC, proto.RoleClient, pairIDArr, &cases)

	otherPairID := seed("other-pair-id", 16)
	var otherPairIDArr [16]byte
	copy(otherPairIDArr[:], otherPairID)
	cases = append(cases, handshakeCase{
		Name:              "verify/pair_mismatch",
		Inputs:            handshakeInputs{PSKHex: hx(psk)},
		VerifyRawHelloHex: hx(helloAgent), VerifyOwnRoleHex: "02", VerifyPairIDHex: hx(otherPairID),
		ExpectError: "pair_mismatch",
	})

	// Reflection: verifier's own role equals the HELLO's role.
	mustReject("verify/role_reflection", psk, helloAgent, proto.RoleAgent, pairIDArr, &cases)

	badVersion := append([]byte(nil), helloAgent...)
	badVersion[0] = 0x02
	mustReject("verify/bad_version_or_mac", psk, badVersion, proto.RoleClient, pairIDArr, &cases)

	badPoint := append([]byte(nil), helloAgent...)
	badPoint[2+16] ^= 0xFF // corrupt one byte inside epk
	mustReject("verify/malformed_point_or_mac", psk, badPoint, proto.RoleClient, pairIDArr, &cases)

	cases = append(cases, handshakeCase{
		Name:              "verify/truncated",
		Inputs:            handshakeInputs{PSKHex: hx(psk)},
		VerifyRawHelloHex: hx(helloAgent[:50]), VerifyOwnRoleHex: "02", VerifyPairIDHex: hx(pairID),
		ExpectError: "bad_length",
	})

	wrongPSK := seed("wrong-psk", 32)
	mustReject("verify/wrong_psk", wrongPSK, helloAgent, proto.RoleClient, pairIDArr, &cases)

	return cases
}

// mustReject verifies that VerifyHello actually rejects rawHello under the
// given psk/ownRole/pairID, records the real error code it produced (not a
// guessed one — check ordering inside VerifyHello determines which check
// fires first), and appends the case.
func mustReject(name string, psk, rawHello []byte, ownRole proto.Role, pairID [16]byte, cases *[]handshakeCase) {
	_, err := proto.VerifyHello(psk, rawHello, pairID, ownRole)
	if err == nil {
		fatal(fmt.Errorf("%s: expected VerifyHello to fail, it succeeded", name))
	}
	*cases = append(*cases, handshakeCase{
		Name:              name,
		Inputs:            handshakeInputs{PSKHex: hx(psk)},
		VerifyRawHelloHex: hx(rawHello),
		VerifyOwnRoleHex:  hx([]byte{byte(ownRole)}),
		VerifyPairIDHex:   hx(pairID[:]),
		ExpectError:       proto.ErrorCode(err),
	})
}

// rawScalar extracts the 32-byte big-endian scalar back out of an
// Ephemeral for publishing in vectors. proto.Ephemeral doesn't expose this
// directly (production code never needs it), so genvectors re-derives it
// via the crypto/ecdh Bytes() accessor through a small type-asserting
// helper kept local to this file.
func rawScalar(e *proto.Ephemeral) []byte {
	return proto.EphemeralRawScalar(e)
}

// --- aead.json ------------------------------------------------------------

type aeadCase struct {
	Name        string `json:"name"`
	KeyHex      string `json:"key_hex"`
	PrefixHex   string `json:"prefix_hex"`
	HeaderHex   string `json:"header_hex"`
	Counter     uint64 `json:"counter"`
	PlaintextHex string `json:"plaintext_hex"`
	// Positive: seal(...) must equal this. Negative (tamper): open(...) of
	// this exact payload against HeaderHex must fail with ExpectError.
	CiphertextPayloadHex string `json:"ciphertext_payload_hex,omitempty"`
	ExpectError          string `json:"expect_error,omitempty"`
}

func genAEAD() []aeadCase {
	key := seed("aead-key", 32)
	prefix := seed("aead-prefix", 4)
	header := []byte{0x01, 0x00} // channel=ciphertext, flags=0

	var cases []aeadCase

	plaintexts := map[string][]byte{
		"empty":      {},
		"one_byte":   []byte{0x42},
		"16kb":       repeatBytes(0xAB, 16*1024),
	}
	counters := []uint64{0, 1, 2, 0xFFFFFFFF, 0x100000000}

	for _, counter := range counters {
		for label, pt := range plaintexts {
			sealer := newTestSealer(key, prefix, counter)
			ct, err := sealer.Seal(header, pt)
			if err != nil {
				fatal(err)
			}
			cases = append(cases, aeadCase{
				Name: fmt.Sprintf("seal/counter_%d/%s", counter, label),
				KeyHex: hx(key), PrefixHex: hx(prefix), HeaderHex: hx(header),
				Counter: counter, PlaintextHex: hx(pt), CiphertextPayloadHex: hx(ct),
			})
		}
	}

	// Tamper cases, built from one good sealed frame at counter 0.
	sealer := newTestSealer(key, prefix, 0)
	good, err := sealer.Seal(header, []byte("authentic frame"))
	if err != nil {
		fatal(err)
	}

	tamperedCT := append([]byte(nil), good...)
	tamperedCT[len(tamperedCT)-1] ^= 0x01
	cases = append(cases, aeadCase{
		Name: "open/tampered_ciphertext", KeyHex: hx(key), PrefixHex: hx(prefix), HeaderHex: hx(header),
		Counter: 0, CiphertextPayloadHex: hx(tamperedCT), ExpectError: "auth_failed",
	})

	cases = append(cases, aeadCase{
		Name: "open/tampered_aad", KeyHex: hx(key), PrefixHex: hx(prefix), HeaderHex: hx([]byte{0x00, 0x00}),
		Counter: 0, CiphertextPayloadHex: hx(good), ExpectError: "auth_failed",
	})

	skipped := append([]byte(nil), good...)
	// good's counter field is already 0; craft a counter=5 payload reusing
	// the same ciphertext bytes to exercise the "gap" rejection path
	// deterministically (the receiver expects 0 first).
	skipped[7] = 5
	cases = append(cases, aeadCase{
		Name: "open/counter_gap", KeyHex: hx(key), PrefixHex: hx(prefix), HeaderHex: hx(header),
		Counter: 5, CiphertextPayloadHex: hx(skipped), ExpectError: "counter_mismatch",
	})

	return cases
}

func repeatBytes(b byte, n int) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = b
	}
	return out
}

// newTestSealer builds a Sealer and fast-forwards its counter to start,
// for constructing vectors at a specific counter value without exposing a
// public "set counter" API on the real type (which must stay append-only
// in production use).
func newTestSealer(key, prefix []byte, startCounter uint64) *proto.Sealer {
	return proto.NewSealerAt(key, prefix, startCounter)
}

// --- reqresp.json -----------------------------------------------------------
//
// Canonical JSON shapes for the REQ/RESP inner-frame payloads (spec §6).
// These aren't cryptographic vectors — they pin down header-list
// canonicalization (order preserved, names lowercase, multi-value as
// repeated pairs) so amallo's dispatch layer and web's relayFetch agree on
// the exact bytes before either exists.

type reqRespCase struct {
	Name       string          `json:"name"`
	Kind       string          `json:"kind"` // "req" | "resp"
	CanonicalJSON json.RawMessage `json:"canonical_json"`
	Notes      string          `json:"notes,omitempty"`
}

func genReqResp() []reqRespCase {
	return []reqRespCase{
		{
			Name: "req/simple_get",
			Kind: "req",
			CanonicalJSON: mustJSON(map[string]any{
				"m": "GET", "p": "/api/tags", "h": [][2]string{},
			}),
		},
		{
			Name: "req/chat_post",
			Kind: "req",
			CanonicalJSON: mustJSON(map[string]any{
				"m": "POST", "p": "/api/chat",
				"h": [][2]string{{"content-type", "application/json"}},
			}),
			Notes: "header names MUST be lowercased by the sender before encoding",
		},
		{
			Name: "req/multi_value_header",
			Kind: "req",
			CanonicalJSON: mustJSON(map[string]any{
				"m": "GET", "p": "/api/tags",
				"h": [][2]string{{"accept", "application/json"}, {"accept", "application/x-ndjson"}},
			}),
			Notes: "multi-value headers are repeated [name,value] pairs, not comma-joined",
		},
		{
			Name: "resp/ndjson_stream",
			Kind: "resp",
			CanonicalJSON: mustJSON(map[string]any{
				"s": 200, "h": [][2]string{{"content-type", "application/x-ndjson"}},
			}),
		},
		{
			Name: "resp/error",
			Kind: "resp",
			CanonicalJSON: mustJSON(map[string]any{
				"s": 502, "h": [][2]string{{"content-type", "text/plain"}},
			}),
		},
	}
}

func mustJSON(v any) json.RawMessage {
	b, err := json.Marshal(v)
	if err != nil {
		fatal(err)
	}
	return b
}

// --- session.json -------------------------------------------------------------
//
// A full ordered transcript for a simulated chat request: REQ, two
// REQ_BODY/RESP_BODY exchanges, then CANCEL — each inner frame sealed
// individually in sequence, using the "handshake/basic" case's derived
// keys. Replayable end-to-end by each implementation as a golden test.

type sessionFrameEntry struct {
	Dir              string `json:"dir"` // "a2w" | "w2a"
	InnerHex         string `json:"inner_hex"`          // plaintext inner-frame encoding, for readability/debugging
	CiphertextHex    string `json:"ciphertext_hex"`     // what actually goes on the wire (outer payload for channel 0x01)
}

type sessionVector struct {
	Name    string               `json:"name"`
	KA2WHex string               `json:"k_a2w_hex"`
	KW2AHex string               `json:"k_w2a_hex"`
	NpA2WHex string              `json:"np_a2w_hex"`
	NpW2AHex string              `json:"np_w2a_hex"`
	Frames  []sessionFrameEntry  `json:"frames"`
}

func genSession() sessionVector {
	pairID := seed("basic-pair-id", 16)
	psk := seed("basic-psk", 32)
	agentEph := deterministicEphemeral("basic-agent-eph")
	webEph := deterministicEphemeral("basic-web-eph")
	agentNonce := seed("basic-agent-nonce", 32)
	webNonce := seed("basic-web-nonce", 32)

	var pairIDArr [16]byte
	copy(pairIDArr[:], pairID)
	var agentNonceArr, webNonceArr [32]byte
	copy(agentNonceArr[:], agentNonce)
	copy(webNonceArr[:], webNonce)

	helloAgent, _ := proto.BuildHello(psk, proto.RoleAgent, pairIDArr, agentEph.PublicKeyBytes(), agentNonceArr)
	helloWeb, _ := proto.BuildHello(psk, proto.RoleClient, pairIDArr, webEph.PublicKeyBytes(), webNonceArr)
	transcript := proto.Transcript(helloAgent, helloWeb)
	ecdhX, _ := agentEph.ECDH(webEph.PublicKeyBytes())
	keys, err := proto.DeriveSession(psk, transcript, ecdhX)
	if err != nil {
		fatal(err)
	}

	a2w, err := proto.NewSealer(keys.KA2W, keys.NPA2W)
	if err != nil {
		fatal(err)
	}
	w2a, err := proto.NewSealer(keys.KW2A, keys.NPW2A)
	if err != nil {
		fatal(err)
	}
	header := []byte{0x01, 0x00}

	type step struct {
		dir   string
		inner wire.InnerFrame
	}
	steps := []step{
		{"w2a", wire.InnerFrame{Type: wire.InnerReq, StreamID: 1, Payload: []byte(`{"m":"POST","p":"/api/chat","h":[["content-type","application/json"]]}`)}},
		{"w2a", wire.InnerFrame{Type: wire.InnerReqBody, StreamID: 1, Payload: []byte(`{"model":"llama3","messages":[{"role":"user","content":"hi"}],"stream":true}`)}},
		{"w2a", wire.InnerFrame{Type: wire.InnerReqEnd, StreamID: 1}},
		{"a2w", wire.InnerFrame{Type: wire.InnerResp, StreamID: 1, Payload: []byte(`{"s":200,"h":[["content-type","application/x-ndjson"]]}`)}},
		{"a2w", wire.InnerFrame{Type: wire.InnerRespBody, StreamID: 1, Payload: []byte(`{"message":{"content":"Hel"}}` + "\n")}},
		{"a2w", wire.InnerFrame{Type: wire.InnerRespBody, StreamID: 1, Payload: []byte(`{"message":{"content":"lo!"}}` + "\n")}},
		{"w2a", wire.InnerFrame{Type: wire.InnerCancel, StreamID: 1, Payload: []byte(`{"code":"user_abort"}`)}},
	}

	var frames []sessionFrameEntry
	for _, s := range steps {
		innerBuf, err := wire.EncodeInner(nil, s.inner)
		if err != nil {
			fatal(err)
		}
		var ct []byte
		if s.dir == "a2w" {
			ct, err = a2w.Seal(header, innerBuf)
		} else {
			ct, err = w2a.Seal(header, innerBuf)
		}
		if err != nil {
			fatal(err)
		}
		frames = append(frames, sessionFrameEntry{Dir: s.dir, InnerHex: hx(innerBuf), CiphertextHex: hx(ct)})
	}

	return sessionVector{
		Name: "session/chat_with_cancel",
		KA2WHex: hx(keys.KA2W), KW2AHex: hx(keys.KW2A),
		NpA2WHex: hx(keys.NPA2W), NpW2AHex: hx(keys.NPW2A),
		Frames: frames,
	}
}
